name: 'Build and push preview docker image'

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  apply_migration:
    uses: ./.github/workflows/apply_migration.yml
    with:
      ENVIRONMENT: staging
    secrets:
      WIREGUARD_CONF: ${{ secrets.WIREGUARD_CONF }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}


  dockerize_and_push:
    name: Build and push preview docker image
    needs: apply_migration
    runs-on: ubuntu-latest
    environment: staging
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Downcase repo
        run: |
          echo "repo=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ env.repo }}:preview
  deploy:
    name: "Deploy to staging"
    runs-on: "ubuntu-latest"
    environment: staging
    needs: dockerize_and_push

    steps:
      - name: "Deploy to staging via webhook"
        run: curl -X POST ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
